### ISSUE TITLE
Bastyon.AppImage not start

### ISSUE THREAD

**Issue by android116** [pocketnetteam/pocketnet.gui#345]
openSUSE 15.3

```
$ ls -la | grep Bastyon
-rwxr-xr-x  1 user users 174377320 фев 13 13:38 Bastyon.AppImage
```

```
$ ./Bastyon.AppImage 
/tmp/.mount_BastyobQ0sZH/AppRun: строка 43: /tmp/.mount_BastyobQ0sZH/: Это каталог
/tmp/.mount_BastyobQ0sZH/AppRun: строка 43: exec: /tmp/.mount_BastyobQ0sZH/: не удаётся запустить: Это каталог
```

**Comment by dtelyukh** [comment]
I confirm on Manjaro 21.2.4 Qonos

**Comment by yashrk** [comment]
I confirm this too, Ubuntu 21.10.

**Comment by ahtamdriver** [comment]
I also confirm Bastyon.AppImage doesn`t work for Linux

**Comment by lostystyg** [comment]
This happens because [here](https://github.com/pocketnetteam/pocketnet.gui/blob/3e223b1a5e9f4d5b6e3a0cf09d639f9b7f07852f/package.json#L184) `${productName}` is not evaluated to 'Bastyon' and is used "as is" for binary name (you can see this after `npm run distl`).
If mount app image and look for its contents - in AppRun the path to binary will look like this: `BIN="$APPDIR/${productName}"` and then executed with `exec "$BIN"`. This results in bash trying to resolve `${productName}` as environment variable that is obviously empty and this causes the error of trying to execute the directory.
Its obviously a bug in AppImage builder that doesn't escape executable names properly and a bug in electron-builder that doesn't set executable name properly.
According to the docs of electron-builder, `executableName` can be deleted from linux target and it will be automatically evaluated to `productName` but this is **wrong** due to a [bug](https://github.com/electron-userland/electron-builder/issues/5848). **Hardcode "Bastyon" for executableName in linux target fully solve the issue so this is a possible solution**.
Possible temporary workaround to launch appimage: `productName=\$\{productName\} ./Bastyon.AppImage`
